# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='followed_by',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='following',
        ),
        migrations.AddField(
            model_name='follower',
            name='user_from',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='following_references', to='users.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follower',
            name='user_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='follower_references', to='users.User'),
            preserve_default=False,
        ),
    ]
